const data = {
  appId: 415,
  identifier: "e6f4f571-bd83-44fd-b22b-fe13e03e3188",
  applicantLeadId: null,
  tranEffDate: null,
  personID: null,
  appStatus: "N",
  appStatusDate: "2023-08-15T00:00:00",
  appNo: "381",
  name: "Saltzman, Sam",
  firstName: "Sam",
  lastName: "Saltzman",
  middleName: "",
  nameSuffix: null,
  namePrefix: null,
  mailAddr: "ssaltzman@pdssoftware.com",
  phoneNo1: null,
  phoneNo2: null,
  addressLine1: null,
  addressLine2: null,
  addressLine3: null,
  addressLine4: null,
  addressCountryCode: null,
  city: null,
  zip: null,
  state: null,
  sentNewAccountEmail: null,
  employmentHistory: [],
  educationHistory: [],
  skills: [],
  interviews: [],
};
