import { images } from '@/exports/images';
import { IProductCard } from '@/interface';

export const product: IProductCard[] = [
  {
    id: '1',
    title: 'Hair Shampoo 10ml',
    imageUrl: images.productImage,
    oldPrice: '5,450',
    newPrice: '2,450',
    newProd: 'New',
    off: '20% Off',
    description:
      'Our 93 percent naturally-derived shampoo contains ginseng and ginger, both of which increase blood flow to the scalp to encourage hair growth. It contains Biotin, keratin, and zinc.',
    weight: '1 KG',
    dimensions: '15 × 12 × 18CM',
    capColors: ['Green', 'Black', 'Red', 'Yellow', 'Blue'],
  },
  {
    id: '2',
    title: 'Man Hair Shampoo 200ml',
    imageUrl: images.productImage,
    oldPrice: '5,000',
    newPrice: '1,450',
    sale: 'Sale',
    description:
      'Our 99 percent naturally-derived shampoo contains ginseng and ginger, both of which increase blood flow to the scalp to encourage hair growth. ',
    weight: '1 KG',
    dimensions: '15 × 12 × 18CM',
    capColors: ['Teal', 'Wheat', 'Red', 'Yellow', 'Blue'],
    imageList: [
      { id: '1', imageUrl: images.productImage },
      { id: '2', imageUrl: images.face2 },
      { id: '3', imageUrl: images.face3 },
      { id: '4', imageUrl: images.face4 },
    ],
  },
  {
    id: '3',
    title: 'Girl Hair',
    imageUrl: images.productImage,
    oldPrice: '2,450',
    newPrice: '750',
    off: '20% Off',
    description:
      'Our 80 percent naturally-derived shampoo contains ginseng and ginger, both of which increase blood flow to the scalp to encourage hair growth. lorememme',
    weight: '1 KG',
    dimensions: '15 × 12 × 18CM',
    capColors: ['Teal', 'Wheat', 'Red', 'Yellow', 'Blue'],
    imageList: [
      { id: '1', imageUrl: images.productImage },
      { id: '2', imageUrl: images.face2 },
      { id: '3', imageUrl: images.face5 },
      { id: '4', imageUrl: images.brand1 },
    ],
  },
  {
    id: '4',
    title: 'Shaving Powder 100ml',
    imageUrl: images.productImage,
    oldPrice: '8,450',
    newPrice: '5,450',
    sale: 'Sale',
    newProd: 'New',
    description:
      'Our 99 percent naturally-derived shampoo contains ginseng and ginger, both of which increase blood flow to the scalp to encourage hair growth. ',
    weight: '1 KG',
    dimensions: '11 × 12 × 21CM',
    capColors: ['Seal', 'coke', 'Red', 'Yellow', 'Blue'],
    imageList: [
      { id: '1', imageUrl: images.productImage },
      { id: '2', imageUrl: images.brand3 },
      { id: '3', imageUrl: images.face3 },
      { id: '4', imageUrl: images.face6 },
    ],
  },
  {
    id: '5',
    title: 'Hair Shampoo 100ml',
    imageUrl: images.productImage,
    oldPrice: '15,450',
    newPrice: '12,450',
    description:
      'Our 99 percent naturally-derived shampoo contains ginseng and ginger, both of which increase blood flow to the scalp to encourage hair growth. ',
    weight: '1 KG',
    dimensions: '15 × 12 × 18CM',
    capColors: ['Teal', 'Wheat', 'Red', 'Yellow', 'Blue'],
    imageList: [
      { id: '1', imageUrl: images.productImage },
      { id: '2', imageUrl: images.face2 },
      { id: '3', imageUrl: images.brand3 },
      { id: '4', imageUrl: images.face1 },
    ],
  },
  {
    id: '6',
    title: 'Hair Shampoo 100ml',
    imageUrl: images.productImage,
    oldPrice: '6,450',
    newPrice: '3,450',
    description:
      'Our 99 percent naturally-derived shampoo contains ginseng and ginger, both of which increase blood flow to the scalp to encourage hair growth. llllllllll',
    weight: '1 KG',
    dimensions: '15 × 12 × 18CM',
    capColors: ['Teal', 'Wheat', 'Red', 'Yellow', 'Blue'],
    imageList: [
      { id: '1', imageUrl: images.productImage },
      { id: '2', imageUrl: images.face2 },
      { id: '3', imageUrl: images.face3 },
      { id: '4', imageUrl: images.face4 },
    ],
  },
  {
    id: '7',
    title: 'Hair Shampoo 100ml',
    imageUrl: images.productImage,
    oldPrice: '3,450',
    newPrice: '1,450',
    description:
      'Our 99 percent naturally-derived shampoo contains ginseng and ginger, both of which increase blood flow to the scalp to encourage hair growth. ',
    weight: '1 KG',
    dimensions: '15 × 12 × 18CM',
    capColors: ['Teal', 'Wheat', 'Red', 'Yellow', 'Blue'],
    imageList: [
      { id: '1', imageUrl: images.productImage },
      { id: '2', imageUrl: images.face2 },
      { id: '3', imageUrl: images.face3 },
      { id: '4', imageUrl: images.face4 },
    ],
  },
  {
    id: '8',
    title: 'Hair Shampoo 100ml',
    imageUrl: images.productImage,
    oldPrice: '23,450',
    newPrice: '20,450',
    description:
      'Our 99 percent naturally-derived shampoo contains ginseng and ginger, both of which increase blood flow to the scalp to encourage hair growth. ',
    weight: '1 KG',
    dimensions: '15 × 12 × 18CM',
    capColors: ['Teal', 'Wheat', 'Red', 'Yellow', 'Blue'],
    imageList: [
      { id: '1', imageUrl: images.productImage },
      { id: '2', imageUrl: images.face2 },
      { id: '3', imageUrl: images.face3 },
      { id: '4', imageUrl: images.face4 },
    ],
  },
  {
    id: '9',
    title: 'Hair Shampoo 100ml',
    imageUrl: images.productImage,
    oldPrice: '18,450',
    newPrice: '10,450',
    description:
      'Our 99 percent naturally-derived shampoo contains ginseng and ginger, both of which increase blood flow to the scalp to encourage hair growth. ',
    weight: '1 KG',
    dimensions: '15 × 12 × 18CM',
    capColors: ['Teal', 'Wheat', 'Red', 'Yellow', 'Blue'],
    imageList: [
      { id: '1', imageUrl: images.productImage },
      { id: '2', imageUrl: images.face2 },
      { id: '3', imageUrl: images.face3 },
      { id: '4', imageUrl: images.face4 },
    ],
  },
  {
    id: '10',
    title: 'Hair Shampoo 100ml',
    imageUrl: images.productImage,
    oldPrice: '7,450',
    newPrice: '4,450',
    description:
      'Our 99 percent naturally-derived shampoo contains ginseng and ginger, both of which increase blood flow to the scalp to encourage hair growth. ',
    weight: '1 KG',
    dimensions: '15 × 12 × 18CM',
    capColors: ['Teal', 'Wheat', 'Red', 'Yellow', 'Blue'],
    imageList: [
      { id: '1', imageUrl: images.productImage },
      { id: '2', imageUrl: images.face2 },
      { id: '3', imageUrl: images.face3 },
      { id: '4', imageUrl: images.face4 },
    ],
  },
];
